# Generated by Django 5.1.5 on 2025-03-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_cost',
        ),
    ]
