# Generated by Django 5.1.5 on 2025-02-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='lab_equipment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='stationery',
        ),
    ]
