# Generated by Django 5.1.5 on 2025-03-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
    ]
