# Generated by Django 5.1.5 on 2025-02-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='labequipment',
            options={'verbose_name_plural': 'Lab Equipment'},
        ),
        migrations.AlterModelOptions(
            name='stationery',
            options={'verbose_name_plural': 'Stationery'},
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2),
        ),
    ]
