# Generated by Django 5.1.5 on 2025-02-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stationery',
            name='image',
        ),
        migrations.AddField(
            model_name='labequipment',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labequipment',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='labequipment',
            name='status',
            field=models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2),
        ),
        migrations.AddField(
            model_name='stationery',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationery',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='stationery',
            name='status',
            field=models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2),
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='books/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.book')),
            ],
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='laboratory/')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.labequipment')),
            ],
        ),
        migrations.CreateModel(
            name='StationeryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='stationery/')),
                ('stationery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.stationery')),
            ],
        ),
    ]
