# Generated by Django 5.1.5 on 2025-02-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_book_image_remove_labequipment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=250, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='devices/')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.device')),
            ],
        ),
    ]
