# Generated by Django 5.1.5 on 2025-02-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_device_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefeature',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.device'),
        ),
    ]
