# Generated by Django 5.1.5 on 2025-02-14 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_book_remove_cartitem_lab_equipment_and_more'),
        ('orders', '0002_remove_orderitem_book_remove_orderitem_lab_equipment_and_more'),
        ('products', '0007_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.RemoveField(
            model_name='deviceimage',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicefeature',
            name='device',
        ),
        migrations.RemoveField(
            model_name='labequipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labimage',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='stationery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stationeryimage',
            name='stationery',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=250, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
        migrations.DeleteModel(
            name='DeviceImage',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceFeature',
        ),
        migrations.DeleteModel(
            name='LabEquipment',
        ),
        migrations.DeleteModel(
            name='LabImage',
        ),
        migrations.DeleteModel(
            name='Stationery',
        ),
        migrations.DeleteModel(
            name='StationeryImage',
        ),
    ]
