# Generated by Django 5.1.5 on 2025-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_main_category_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Stationery', 'Stationery'), ('Technology', 'Technology'), ('Books', 'Books'), ('Lab Equipment', 'Lab Equipment')], max_length=50, null=True),
        ),
    ]
