# Generated by Django 5.1.5 on 2025-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_best_seller_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('top', 'Top Banner'), ('middle', 'Middle Banner'), ('bottom', 'Bottom Banner')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Stationery', 'Stationery'), ('Lab Equipment', 'Lab Equipment'), ('Books', 'Books')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2),
        ),
    ]
