# Generated by Django 5.1.5 on 2025-02-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Stationery', 'Stationery'), ('Lab Equipment', 'Lab Equipment'), ('Books', 'Books'), ('Technology', 'Technology')], max_length=50, null=True),
        ),
    ]
