# Generated by Django 5.1.5 on 2025-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Lab Equipment', 'Lab Equipment'), ('Books', 'Books'), ('Stationery', 'Stationery')], max_length=50, null=True),
        ),
    ]
