# Generated by Django 5.1.5 on 2025-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_main_category_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Books', 'Books'), ('Stationery', 'Stationery'), ('Lab Equipment', 'Lab Equipment')], max_length=50, null=True),
        ),
    ]
