# Generated by Django 5.1.5 on 2025-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_main_category_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Stationery', 'Stationery'), ('Lab Equipment', 'Lab Equipment'), ('Technology', 'Technology'), ('Books', 'Books')], max_length=50, null=True),
        ),
    ]
