# Generated by Django 5.1.5 on 2025-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Lab Equipment', 'Lab Equipment'), ('Technology', 'Technology'), ('Stationery', 'Stationery')], max_length=50, null=True),
        ),
    ]
