# Generated by Django 5.1.5 on 2025-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_banner_link_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Lab Equipment', 'Lab Equipment'), ('Stationery', 'Stationery'), ('Technology', 'Technology'), ('Books', 'Books')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2),
        ),
    ]
