# Generated by Django 5.1.5 on 2025-03-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_main_category_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Books', 'Books'), ('Lab Equipment', 'Lab Equipment'), ('Stationery', 'Stationery'), ('Technology', 'Technology')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DT', 'Draft'), ('PB', 'Published')], default='DT', max_length=2),
        ),
    ]
